name: frontend workflow

on:
  push:
    branches:
      feature/cicd

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore node modules cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: node-cache

      - name: Run lint
        run: npx eslint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: node-cache
      
      - name: Install Angular CLI (if needed for global commands)
        run: npm install -g @angular/cli
      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser firefox xvfb
          export CHROME_BIN=/usr/bin/chromium-browser
          export FIREFOX_BIN=/usr/bin/firefox
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Run unit tests
        run: npm run test -- --browsers=ChromeHeadless --no-watch


  # deploy-dev:
  #   stage: deploy
  #   variables:
  #     NODE_ENV: development
  #   needs: ["assemble"]
  #   before_script:
  #     - echo "Deploying to $CI_ENVIRONMENT_NAME"
  #   script:
  #     - echo "Making actions to deploy to dev"
  #     - echo "Deployed to $CI_ENVIRONMENT_NAME"
  #   environment:
  #     name: development
