name: frontend workflow

on:
  push:
    branches:
      feature/cicd

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore node modules cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Run lint
        run: npx eslint


  # test:
  #   stage: quality
  #   needs: ["install"]
  #   before_script:
  #     # Download Chrome
  #     - apk add chromium
  #     - export CHROME_BIN=/usr/bin/chromium-browser
  #     - export CHROME_PATH=/usr/lib/chromium/
  #     # Download Firefox
  #     - apk add firefox-esr
  #     - export FIREFOX_BIN=/usr/bin/firefox
  #     - export FIREFOX_PATH=/usr/lib/firefox/
  #     # X Server
  #     - apk add xvfb
  #     - export DISPLAY=:99
  #     - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  #   script:
  #     - npm run test -- --browsers=Headless_Chrome --no-watch
  #   cache:
  #     key:
  #       files:
  #         - package.json
  #     paths:
  #       - node_modules
  #     policy: pull

  # assemble:
  #   stage: assemble
  #   needs: ["test", "lint"]
  #   script:
  #     - npm run build
  #   artifacts:
  #     paths:
  #       - $CI_PROJECT_DIR/dist
  #   cache:
  #     key:
  #       files:
  #         - package.json
  #     paths:
  #       - node_modules
  #     policy: pull


  # deploy-dev:
  #   stage: deploy
  #   variables:
  #     NODE_ENV: development
  #   needs: ["assemble"]
  #   before_script:
  #     - echo "Deploying to $CI_ENVIRONMENT_NAME"
  #   script:
  #     - echo "Making actions to deploy to dev"
  #     - echo "Deployed to $CI_ENVIRONMENT_NAME"
  #   environment:
  #     name: development
